Repository GoodGameRuler/unitrack_v3, pull requests merged in 2024-06, with the labels that each got.

#55 Add filter functionality and fix minor UI issues
  app/units/page.jsx
  app/units/units.css
Labels: bug, enhancement, not noob friendly

#66 Fix React warning: use defaultValue instead of selected
  app/degreePlanner/degreePlanner.css
  app/degreePlanner/page.jsx
Labels: bug, good first issue

#68 Enhance UI with new hover effects, cursor changes, and other improvements
  app/units/units.css
Labels: enhancement, good first issue

#75 Only show details form in degree planner when it has not been submitted
  app/degreePlanner/page.jsx
  app/degreePlanner/planner.jsx
Labels: bug, enhancement, help wanted
