Repository GoodGameRuler/unitrack_v3, pull requests merged in 2024-05, with the labels that each got.

#1 Fixing typo for planner file name
  app/degreePlanner/page.js
  app/degreePlanner/planner.js
Labels: bug

#6 Finish UI for About Us page
  app/index.css
  app/page.js
  app/reset.css
  public/images/antriksh.png
  public/images/devu.jpeg
  public/images/github-mark.svg
  public/images/jenny.png
  public/images/parth.jpeg
  public/images/udit.jpeg
Labels: enhancement

#11 Fix styling for nav bar
  app/navbar.css
  app/navbar.js
Labels: bug

#16 Fix sizing issue on mozilla and chrome and refined content
  app/index.css
  app/page.js
  app/reset.css
  public/images/antriksh.png
  public/images/devu.jpeg
  public/images/parth.jpeg
Labels: bug, good first issue

#18 Reduce size of nav bar
  app/global.css
  app/navbar.css
Labels: bug, good first issue

#28 Fixing UI for degree details form - submit form button
  app/degreePlanner/degreePlanner.css
  app/degreePlanner/page.jsx
Labels: bug, good first issue

#44 Patch documentation
  README.md
Labels: enhancement, maintainer only

#29 #27 Align Degree Details Form to Center
  app/degreePlanner/degreePlanner.css
  app/global.css
Labels: bug, good first issue

#45 Change spacing and alignment in units page
  app/units/page.jsx
  app/units/units.css
Labels: bug, good first issue

#31 Minor UI changes to search bar colors and focus
  app/units/units.css
Labels: bug, good first issue

#53 #52 Add web analytics to vercel
  app/layout.jsx
  package-lock.json
  package.json
Labels: enhancement, maintainer only

#58 Include vercel dev for maintainers in readme
  README.md
Labels: documentation, maintainer only

#63 Add speed insights to analytics on vercel for further testing
  app/layout.jsx
  package-lock.json
  package.json
Labels: enhancement, maintainer only

#59 Create a basic style guide
  STYLE.md
Labels: documentation
